# Generated by Django 3.1.4 on 2020-12-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_book_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_app.library'),
        ),
    ]
